// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.superbfowle.tass.enervate
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// A registered drain or expenditure of Tass. 'To enervate' literally means to draw the sinew (the nerve, the current-carrying conduit) out of a node — to tap the tass and withdraw its current. Each enervate reduces the available quintessence in the referenced tassilize record.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "com.superbfowle.tass.enervate",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Enervate<S: BosStr = DefaultStr> {
    ///Quintessence withdrawn from the tass
    pub amount: i64,
    ///Timestamp of the enervation
    pub created_at: Datetime,
    ///Optional: what the withdrawn quintessence was spent on
    #[serde(skip_serializing_if = "Option::is_none")]
    pub purpose: Option<S>,
    ///AT-URI of the com.superbfowle.tass.tassilize record being drained
    pub tass: AtUri<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct EnervateGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Enervate<S>,
}

impl<S: BosStr> Enervate<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, EnervateRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct EnervateRecord;
impl XrpcResp for EnervateRecord {
    const NSID: &'static str = "com.superbfowle.tass.enervate";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = EnervateGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<EnervateGetRecordOutput<S>> for Enervate<S> {
    fn from(output: EnervateGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Enervate<S> {
    const NSID: &'static str = "com.superbfowle.tass.enervate";
    type Record = EnervateRecord;
}

impl Collection for EnervateRecord {
    const NSID: &'static str = "com.superbfowle.tass.enervate";
    type Record = EnervateRecord;
}

impl<S: BosStr> LexiconSchema for Enervate<S> {
    fn nsid() -> &'static str {
        "com.superbfowle.tass.enervate"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_com_superbfowle_tass_enervate()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.amount;
            if *value > 100i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("amount"),
                    max: 100i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.amount;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("amount"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.purpose {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 500usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("purpose"),
                    max: 500usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.purpose {
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 250usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("purpose"),
                        max: 250usize,
                        actual: count,
                    });
                }
            }
        }
        Ok(())
    }
}

pub mod enervate_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Amount;
        type CreatedAt;
        type Tass;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Amount = Unset;
        type CreatedAt = Unset;
        type Tass = Unset;
    }
    ///State transition - sets the `amount` field to Set
    pub struct SetAmount<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetAmount<St> {}
    impl<St: State> State for SetAmount<St> {
        type Amount = Set<members::amount>;
        type CreatedAt = St::CreatedAt;
        type Tass = St::Tass;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type Amount = St::Amount;
        type CreatedAt = Set<members::created_at>;
        type Tass = St::Tass;
    }
    ///State transition - sets the `tass` field to Set
    pub struct SetTass<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTass<St> {}
    impl<St: State> State for SetTass<St> {
        type Amount = St::Amount;
        type CreatedAt = St::CreatedAt;
        type Tass = Set<members::tass>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `amount` field
        pub struct amount(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `tass` field
        pub struct tass(());
    }
}

/// Builder for constructing an instance of this type.
pub struct EnervateBuilder<St: enervate_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<Datetime>, Option<S>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl Enervate<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> EnervateBuilder<enervate_state::Empty, DefaultStr> {
        EnervateBuilder::new()
    }
}

impl<S: BosStr> Enervate<S> {
    /// Create a new builder for this type
    pub fn builder() -> EnervateBuilder<enervate_state::Empty, S> {
        EnervateBuilder::builder()
    }
}

impl EnervateBuilder<enervate_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        EnervateBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> EnervateBuilder<enervate_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        EnervateBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> EnervateBuilder<St, S>
where
    St: enervate_state::State,
    St::Amount: enervate_state::IsUnset,
{
    /// Set the `amount` field (required)
    pub fn amount(
        mut self,
        value: impl Into<i64>,
    ) -> EnervateBuilder<enervate_state::SetAmount<St>, S> {
        self._fields.0 = Option::Some(value.into());
        EnervateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> EnervateBuilder<St, S>
where
    St: enervate_state::State,
    St::CreatedAt: enervate_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> EnervateBuilder<enervate_state::SetCreatedAt<St>, S> {
        self._fields.1 = Option::Some(value.into());
        EnervateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: enervate_state::State, S: BosStr> EnervateBuilder<St, S> {
    /// Set the `purpose` field (optional)
    pub fn purpose(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `purpose` field to an Option value (optional)
    pub fn maybe_purpose(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> EnervateBuilder<St, S>
where
    St: enervate_state::State,
    St::Tass: enervate_state::IsUnset,
{
    /// Set the `tass` field (required)
    pub fn tass(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> EnervateBuilder<enervate_state::SetTass<St>, S> {
        self._fields.3 = Option::Some(value.into());
        EnervateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> EnervateBuilder<St, S>
where
    St: enervate_state::State,
    St::Amount: enervate_state::IsSet,
    St::CreatedAt: enervate_state::IsSet,
    St::Tass: enervate_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Enervate<S> {
        Enervate {
            amount: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            purpose: self._fields.2,
            tass: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Enervate<S> {
        Enervate {
            amount: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            purpose: self._fields.2,
            tass: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_com_superbfowle_tass_enervate() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("com.superbfowle.tass.enervate"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A registered drain or expenditure of Tass. 'To enervate' literally means to draw the sinew (the nerve, the current-carrying conduit) out of a node — to tap the tass and withdraw its current. Each enervate reduces the available quintessence in the referenced tassilize record.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("tass"), SmolStr::new_static("amount"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("amount"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(100i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Timestamp of the enervation"),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("purpose"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Optional: what the withdrawn quintessence was spent on",
                                        ),
                                    ),
                                    max_length: Some(500usize),
                                    max_graphemes: Some(250usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("tass"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "AT-URI of the com.superbfowle.tass.tassilize record being drained",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::AtUri),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}