// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.superbfowle.tass.form
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// A named Tass form — the coincidental shape crystallized quintessence takes in reality. Defines the materialize cost (q spent to bring the form into being) and total capacity (max q the form can hold). Referenced from tassilize records via formRef.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "com.superbfowle.tass.form",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Form<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<S>,
    ///Quintessence spent to bring this form into being (the cost side of the cost/capacity ratio)
    pub materialize_cost: i64,
    ///Display name (e.g. 'Silver Coin', 'Tass Car')
    pub name: S,
    ///Optional convenience tag (e.g. 'tiny', 'small', 'medium', 'large', 'huge')
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size_category: Option<S>,
    ///Maximum quintessence this form can hold once materialized
    pub total_capacity: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct FormGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Form<S>,
}

impl<S: BosStr> Form<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, FormRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct FormRecord;
impl XrpcResp for FormRecord {
    const NSID: &'static str = "com.superbfowle.tass.form";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = FormGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<FormGetRecordOutput<S>> for Form<S> {
    fn from(output: FormGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Form<S> {
    const NSID: &'static str = "com.superbfowle.tass.form";
    type Record = FormRecord;
}

impl Collection for FormRecord {
    const NSID: &'static str = "com.superbfowle.tass.form";
    type Record = FormRecord;
}

impl<S: BosStr> LexiconSchema for Form<S> {
    fn nsid() -> &'static str {
        "com.superbfowle.tass.form"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_com_superbfowle_tass_form()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.description {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 2000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("description"),
                    max: 2000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.description {
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 1000usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("description"),
                        max: 1000usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.materialize_cost;
            if *value > 100i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("materialize_cost"),
                    max: 100i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.materialize_cost;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("materialize_cost"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.name;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 100usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("name"),
                    max: 100usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.name;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 50usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("name"),
                        max: 50usize,
                        actual: count,
                    });
                }
            }
        }
        if let Some(ref value) = self.size_category {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 32usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("size_category"),
                    max: 32usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.total_capacity;
            if *value > 1000i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("total_capacity"),
                    max: 1000i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.total_capacity;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("total_capacity"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod form_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type MaterializeCost;
        type Name;
        type TotalCapacity;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type MaterializeCost = Unset;
        type Name = Unset;
        type TotalCapacity = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type MaterializeCost = St::MaterializeCost;
        type Name = St::Name;
        type TotalCapacity = St::TotalCapacity;
    }
    ///State transition - sets the `materialize_cost` field to Set
    pub struct SetMaterializeCost<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetMaterializeCost<St> {}
    impl<St: State> State for SetMaterializeCost<St> {
        type CreatedAt = St::CreatedAt;
        type MaterializeCost = Set<members::materialize_cost>;
        type Name = St::Name;
        type TotalCapacity = St::TotalCapacity;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetName<St> {}
    impl<St: State> State for SetName<St> {
        type CreatedAt = St::CreatedAt;
        type MaterializeCost = St::MaterializeCost;
        type Name = Set<members::name>;
        type TotalCapacity = St::TotalCapacity;
    }
    ///State transition - sets the `total_capacity` field to Set
    pub struct SetTotalCapacity<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTotalCapacity<St> {}
    impl<St: State> State for SetTotalCapacity<St> {
        type CreatedAt = St::CreatedAt;
        type MaterializeCost = St::MaterializeCost;
        type Name = St::Name;
        type TotalCapacity = Set<members::total_capacity>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `materialize_cost` field
        pub struct materialize_cost(());
        ///Marker type for the `name` field
        pub struct name(());
        ///Marker type for the `total_capacity` field
        pub struct total_capacity(());
    }
}

/// Builder for constructing an instance of this type.
pub struct FormBuilder<St: form_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Datetime>,
        Option<S>,
        Option<i64>,
        Option<S>,
        Option<S>,
        Option<i64>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Form<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> FormBuilder<form_state::Empty, DefaultStr> {
        FormBuilder::new()
    }
}

impl<S: BosStr> Form<S> {
    /// Create a new builder for this type
    pub fn builder() -> FormBuilder<form_state::Empty, S> {
        FormBuilder::builder()
    }
}

impl FormBuilder<form_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        FormBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> FormBuilder<form_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        FormBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> FormBuilder<St, S>
where
    St: form_state::State,
    St::CreatedAt: form_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> FormBuilder<form_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        FormBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: form_state::State, S: BosStr> FormBuilder<St, S> {
    /// Set the `description` field (optional)
    pub fn description(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `description` field to an Option value (optional)
    pub fn maybe_description(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> FormBuilder<St, S>
where
    St: form_state::State,
    St::MaterializeCost: form_state::IsUnset,
{
    /// Set the `materializeCost` field (required)
    pub fn materialize_cost(
        mut self,
        value: impl Into<i64>,
    ) -> FormBuilder<form_state::SetMaterializeCost<St>, S> {
        self._fields.2 = Option::Some(value.into());
        FormBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> FormBuilder<St, S>
where
    St: form_state::State,
    St::Name: form_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<S>,
    ) -> FormBuilder<form_state::SetName<St>, S> {
        self._fields.3 = Option::Some(value.into());
        FormBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: form_state::State, S: BosStr> FormBuilder<St, S> {
    /// Set the `sizeCategory` field (optional)
    pub fn size_category(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `sizeCategory` field to an Option value (optional)
    pub fn maybe_size_category(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St, S: BosStr> FormBuilder<St, S>
where
    St: form_state::State,
    St::TotalCapacity: form_state::IsUnset,
{
    /// Set the `totalCapacity` field (required)
    pub fn total_capacity(
        mut self,
        value: impl Into<i64>,
    ) -> FormBuilder<form_state::SetTotalCapacity<St>, S> {
        self._fields.5 = Option::Some(value.into());
        FormBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> FormBuilder<St, S>
where
    St: form_state::State,
    St::CreatedAt: form_state::IsSet,
    St::MaterializeCost: form_state::IsSet,
    St::Name: form_state::IsSet,
    St::TotalCapacity: form_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Form<S> {
        Form {
            created_at: self._fields.0.unwrap(),
            description: self._fields.1,
            materialize_cost: self._fields.2.unwrap(),
            name: self._fields.3.unwrap(),
            size_category: self._fields.4,
            total_capacity: self._fields.5.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Form<S> {
        Form {
            created_at: self._fields.0.unwrap(),
            description: self._fields.1,
            materialize_cost: self._fields.2.unwrap(),
            name: self._fields.3.unwrap(),
            size_category: self._fields.4,
            total_capacity: self._fields.5.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_com_superbfowle_tass_form() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("com.superbfowle.tass.form"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A named Tass form — the coincidental shape crystallized quintessence takes in reality. Defines the materialize cost (q spent to bring the form into being) and total capacity (max q the form can hold). Referenced from tassilize records via formRef.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("name"),
                                SmolStr::new_static("materializeCost"),
                                SmolStr::new_static("totalCapacity"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("description"),
                                LexObjectProperty::String(LexString {
                                    max_length: Some(2000usize),
                                    max_graphemes: Some(1000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("materializeCost"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(100i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("name"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Display name (e.g. 'Silver Coin', 'Tass Car')",
                                        ),
                                    ),
                                    max_length: Some(100usize),
                                    max_graphemes: Some(50usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("sizeCategory"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Optional convenience tag (e.g. 'tiny', 'small', 'medium', 'large', 'huge')",
                                        ),
                                    ),
                                    max_length: Some(32usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("totalCapacity"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(1000i64),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}