// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.superbfowle.tass.meditate
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// Record of a Mage meditating at a Node to pull quintessence from its ambiance into their own pattern. Limited by Avatar rating (enforced out-of-band by the mage's sheet, not by this schema).

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "com.superbfowle.tass.meditate",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Meditate<S: BosStr = DefaultStr> {
    ///Quintessence drawn from the Node's ambient field
    pub amount: i64,
    ///Timestamp of the meditation
    pub created_at: Datetime,
    ///AT-URI of the Node meditated at
    pub node: AtUri<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct MeditateGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Meditate<S>,
}

impl<S: BosStr> Meditate<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, MeditateRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct MeditateRecord;
impl XrpcResp for MeditateRecord {
    const NSID: &'static str = "com.superbfowle.tass.meditate";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = MeditateGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<MeditateGetRecordOutput<S>> for Meditate<S> {
    fn from(output: MeditateGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Meditate<S> {
    const NSID: &'static str = "com.superbfowle.tass.meditate";
    type Record = MeditateRecord;
}

impl Collection for MeditateRecord {
    const NSID: &'static str = "com.superbfowle.tass.meditate";
    type Record = MeditateRecord;
}

impl<S: BosStr> LexiconSchema for Meditate<S> {
    fn nsid() -> &'static str {
        "com.superbfowle.tass.meditate"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_com_superbfowle_tass_meditate()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.amount;
            if *value > 20i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("amount"),
                    max: 20i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.amount;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("amount"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod meditate_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Amount;
        type CreatedAt;
        type Node;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Amount = Unset;
        type CreatedAt = Unset;
        type Node = Unset;
    }
    ///State transition - sets the `amount` field to Set
    pub struct SetAmount<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetAmount<St> {}
    impl<St: State> State for SetAmount<St> {
        type Amount = Set<members::amount>;
        type CreatedAt = St::CreatedAt;
        type Node = St::Node;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type Amount = St::Amount;
        type CreatedAt = Set<members::created_at>;
        type Node = St::Node;
    }
    ///State transition - sets the `node` field to Set
    pub struct SetNode<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetNode<St> {}
    impl<St: State> State for SetNode<St> {
        type Amount = St::Amount;
        type CreatedAt = St::CreatedAt;
        type Node = Set<members::node>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `amount` field
        pub struct amount(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `node` field
        pub struct node(());
    }
}

/// Builder for constructing an instance of this type.
pub struct MeditateBuilder<St: meditate_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<Datetime>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl Meditate<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> MeditateBuilder<meditate_state::Empty, DefaultStr> {
        MeditateBuilder::new()
    }
}

impl<S: BosStr> Meditate<S> {
    /// Create a new builder for this type
    pub fn builder() -> MeditateBuilder<meditate_state::Empty, S> {
        MeditateBuilder::builder()
    }
}

impl MeditateBuilder<meditate_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        MeditateBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> MeditateBuilder<meditate_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        MeditateBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MeditateBuilder<St, S>
where
    St: meditate_state::State,
    St::Amount: meditate_state::IsUnset,
{
    /// Set the `amount` field (required)
    pub fn amount(
        mut self,
        value: impl Into<i64>,
    ) -> MeditateBuilder<meditate_state::SetAmount<St>, S> {
        self._fields.0 = Option::Some(value.into());
        MeditateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MeditateBuilder<St, S>
where
    St: meditate_state::State,
    St::CreatedAt: meditate_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> MeditateBuilder<meditate_state::SetCreatedAt<St>, S> {
        self._fields.1 = Option::Some(value.into());
        MeditateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MeditateBuilder<St, S>
where
    St: meditate_state::State,
    St::Node: meditate_state::IsUnset,
{
    /// Set the `node` field (required)
    pub fn node(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> MeditateBuilder<meditate_state::SetNode<St>, S> {
        self._fields.2 = Option::Some(value.into());
        MeditateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MeditateBuilder<St, S>
where
    St: meditate_state::State,
    St::Amount: meditate_state::IsSet,
    St::CreatedAt: meditate_state::IsSet,
    St::Node: meditate_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Meditate<S> {
        Meditate {
            amount: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            node: self._fields.2.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Meditate<S> {
        Meditate {
            amount: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            node: self._fields.2.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_com_superbfowle_tass_meditate() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("com.superbfowle.tass.meditate"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Record of a Mage meditating at a Node to pull quintessence from its ambiance into their own pattern. Limited by Avatar rating (enforced out-of-band by the mage's sheet, not by this schema).",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("node"), SmolStr::new_static("amount"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("amount"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(20i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Timestamp of the meditation"),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("node"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("AT-URI of the Node meditated at"),
                                    ),
                                    format: Some(LexStringFormat::AtUri),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}