// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.superbfowle.tass.resonance
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::com_superbfowle::tass::resonance;
/// A canonical resonance type declaration. Each record defines one named axis that entities can be characterized along. Tagged with a 'system' so multiple game cosmologies coexist:
///   - mage: Dynamic (Wyld), Static (Weaver), Primordial (Wyrm) — the Triat
///   - reverie: entropy, liberty, skeptic, receptive, authority, oblivion
///   - custom: anything else
/// Entities reference these by at-uri in #resonanceValue.axis, OR they use freeform axis names.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "com.superbfowle.tass.resonance",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Resonance<S: BosStr = DefaultStr> {
    ///Optional cosmological referent (e.g. 'Wyld', 'Weaver', 'Wyrm' for Mage Triat)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cosmology: Option<S>,
    pub created_at: Datetime,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<S>,
    ///Canonical name (e.g. 'Dynamic', 'Static', 'Primordial', 'entropy', 'liberty')
    pub name: S,
    ///Name or at-uri of the canonical opposite pole (e.g. Dynamic ↔ Static)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub opposed_to: Option<S>,
    ///Game system this canonical belongs to ('mage', 'reverie', 'custom', ...)
    pub system: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ResonanceGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Resonance<S>,
}

/// An entity's resonance characterization. EITHER 'ref' (at-uri pointing to a published named profile) OR 'values' (inline axis/value pairs). Both unset = no resonance specified. Both set = inline values augment the referenced profile (uncommon).

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ResonanceProfile<S: BosStr = DefaultStr> {
    ///AT-URI of a published named resonance profile
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<AtUri<S>>,
    ///Inline axis/value pairs (freeform, no named record)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<resonance::ResonanceValue<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// A single (axis, value) pair characterizing an entity along one resonance. 'axis' is either an at-uri pointing to a canonical resonance record in this collection, OR a freeform string name (when the entity is characterized ad-hoc without referencing a published record). 'value' is the entity's position on this axis, stored as a fixed-point integer in range [-1000, 1000] representing the float [-1.0, 1.0] (i.e. actual_value = stored / 1000). Atproto lexicons have no native float type; this is the canonical workaround.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ResonanceValue<S: BosStr = DefaultStr> {
    ///AT-URI of a canonical resonance record, OR freeform axis name
    pub axis: S,
    ///Position on this axis, fixed-point: actual_value = stored / 1000 (so 500 = 0.5, -250 = -0.25)
    pub value: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

impl<S: BosStr> Resonance<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, ResonanceRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct ResonanceRecord;
impl XrpcResp for ResonanceRecord {
    const NSID: &'static str = "com.superbfowle.tass.resonance";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ResonanceGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<ResonanceGetRecordOutput<S>> for Resonance<S> {
    fn from(output: ResonanceGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Resonance<S> {
    const NSID: &'static str = "com.superbfowle.tass.resonance";
    type Record = ResonanceRecord;
}

impl Collection for ResonanceRecord {
    const NSID: &'static str = "com.superbfowle.tass.resonance";
    type Record = ResonanceRecord;
}

impl<S: BosStr> LexiconSchema for Resonance<S> {
    fn nsid() -> &'static str {
        "com.superbfowle.tass.resonance"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_com_superbfowle_tass_resonance()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.cosmology {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 50usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("cosmology"),
                    max: 50usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.description {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 2000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("description"),
                    max: 2000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.description {
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 1000usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("description"),
                        max: 1000usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.name;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 50usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("name"),
                    max: 50usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.name;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 32usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("name"),
                        max: 32usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.system;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 50usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("system"),
                    max: 50usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for ResonanceProfile<S> {
    fn nsid() -> &'static str {
        "com.superbfowle.tass.resonance"
    }
    fn def_name() -> &'static str {
        "resonanceProfile"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_com_superbfowle_tass_resonance()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for ResonanceValue<S> {
    fn nsid() -> &'static str {
        "com.superbfowle.tass.resonance"
    }
    fn def_name() -> &'static str {
        "resonanceValue"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_com_superbfowle_tass_resonance()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.value;
            if *value > 1000i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("value"),
                    max: 1000i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.value;
            if *value < -1000i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("value"),
                    min: -1000i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod resonance_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Name;
        type System;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Name = Unset;
        type System = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Name = St::Name;
        type System = St::System;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetName<St> {}
    impl<St: State> State for SetName<St> {
        type CreatedAt = St::CreatedAt;
        type Name = Set<members::name>;
        type System = St::System;
    }
    ///State transition - sets the `system` field to Set
    pub struct SetSystem<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSystem<St> {}
    impl<St: State> State for SetSystem<St> {
        type CreatedAt = St::CreatedAt;
        type Name = St::Name;
        type System = Set<members::system>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `name` field
        pub struct name(());
        ///Marker type for the `system` field
        pub struct system(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ResonanceBuilder<St: resonance_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<Datetime>, Option<S>, Option<S>, Option<S>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl Resonance<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ResonanceBuilder<resonance_state::Empty, DefaultStr> {
        ResonanceBuilder::new()
    }
}

impl<S: BosStr> Resonance<S> {
    /// Create a new builder for this type
    pub fn builder() -> ResonanceBuilder<resonance_state::Empty, S> {
        ResonanceBuilder::builder()
    }
}

impl ResonanceBuilder<resonance_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ResonanceBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ResonanceBuilder<resonance_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ResonanceBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: resonance_state::State, S: BosStr> ResonanceBuilder<St, S> {
    /// Set the `cosmology` field (optional)
    pub fn cosmology(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cosmology` field to an Option value (optional)
    pub fn maybe_cosmology(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> ResonanceBuilder<St, S>
where
    St: resonance_state::State,
    St::CreatedAt: resonance_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> ResonanceBuilder<resonance_state::SetCreatedAt<St>, S> {
        self._fields.1 = Option::Some(value.into());
        ResonanceBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: resonance_state::State, S: BosStr> ResonanceBuilder<St, S> {
    /// Set the `description` field (optional)
    pub fn description(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `description` field to an Option value (optional)
    pub fn maybe_description(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> ResonanceBuilder<St, S>
where
    St: resonance_state::State,
    St::Name: resonance_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<S>,
    ) -> ResonanceBuilder<resonance_state::SetName<St>, S> {
        self._fields.3 = Option::Some(value.into());
        ResonanceBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: resonance_state::State, S: BosStr> ResonanceBuilder<St, S> {
    /// Set the `opposedTo` field (optional)
    pub fn opposed_to(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `opposedTo` field to an Option value (optional)
    pub fn maybe_opposed_to(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St, S: BosStr> ResonanceBuilder<St, S>
where
    St: resonance_state::State,
    St::System: resonance_state::IsUnset,
{
    /// Set the `system` field (required)
    pub fn system(
        mut self,
        value: impl Into<S>,
    ) -> ResonanceBuilder<resonance_state::SetSystem<St>, S> {
        self._fields.5 = Option::Some(value.into());
        ResonanceBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ResonanceBuilder<St, S>
where
    St: resonance_state::State,
    St::CreatedAt: resonance_state::IsSet,
    St::Name: resonance_state::IsSet,
    St::System: resonance_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Resonance<S> {
        Resonance {
            cosmology: self._fields.0,
            created_at: self._fields.1.unwrap(),
            description: self._fields.2,
            name: self._fields.3.unwrap(),
            opposed_to: self._fields.4,
            system: self._fields.5.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> Resonance<S> {
        Resonance {
            cosmology: self._fields.0,
            created_at: self._fields.1.unwrap(),
            description: self._fields.2,
            name: self._fields.3.unwrap(),
            opposed_to: self._fields.4,
            system: self._fields.5.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_com_superbfowle_tass_resonance() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("com.superbfowle.tass.resonance"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A canonical resonance type declaration. Each record defines one named axis that entities can be characterized along. Tagged with a 'system' so multiple game cosmologies coexist:\n  - mage: Dynamic (Wyld), Static (Weaver), Primordial (Wyrm) — the Triat\n  - reverie: entropy, liberty, skeptic, receptive, authority, oblivion\n  - custom: anything else\nEntities reference these by at-uri in #resonanceValue.axis, OR they use freeform axis names.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("name"), SmolStr::new_static("system"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("cosmology"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Optional cosmological referent (e.g. 'Wyld', 'Weaver', 'Wyrm' for Mage Triat)",
                                        ),
                                    ),
                                    max_length: Some(50usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("description"),
                                LexObjectProperty::String(LexString {
                                    max_length: Some(2000usize),
                                    max_graphemes: Some(1000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("name"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Canonical name (e.g. 'Dynamic', 'Static', 'Primordial', 'entropy', 'liberty')",
                                        ),
                                    ),
                                    max_length: Some(50usize),
                                    max_graphemes: Some(32usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("opposedTo"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Name or at-uri of the canonical opposite pole (e.g. Dynamic ↔ Static)",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("system"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Game system this canonical belongs to ('mage', 'reverie', 'custom', ...)",
                                        ),
                                    ),
                                    max_length: Some(50usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("resonanceProfile"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "An entity's resonance characterization. EITHER 'ref' (at-uri pointing to a published named profile) OR 'values' (inline axis/value pairs). Both unset = no resonance specified. Both set = inline values augment the referenced profile (uncommon).",
                        ),
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("ref"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "AT-URI of a published named resonance profile",
                                    ),
                                ),
                                format: Some(LexStringFormat::AtUri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("values"),
                            LexObjectProperty::Array(LexArray {
                                description: Some(
                                    CowStr::new_static(
                                        "Inline axis/value pairs (freeform, no named record)",
                                    ),
                                ),
                                items: LexArrayItem::Ref(LexRef {
                                    r#ref: CowStr::new_static("#resonanceValue"),
                                    ..Default::default()
                                }),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("resonanceValue"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "A single (axis, value) pair characterizing an entity along one resonance. 'axis' is either an at-uri pointing to a canonical resonance record in this collection, OR a freeform string name (when the entity is characterized ad-hoc without referencing a published record). 'value' is the entity's position on this axis, stored as a fixed-point integer in range [-1000, 1000] representing the float [-1.0, 1.0] (i.e. actual_value = stored / 1000). Atproto lexicons have no native float type; this is the canonical workaround.",
                        ),
                    ),
                    required: Some(
                        vec![SmolStr::new_static("axis"), SmolStr::new_static("value")],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("axis"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "AT-URI of a canonical resonance record, OR freeform axis name",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("value"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(-1000i64),
                                maximum: Some(1000i64),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod resonance_value_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Axis;
        type Value;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Axis = Unset;
        type Value = Unset;
    }
    ///State transition - sets the `axis` field to Set
    pub struct SetAxis<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetAxis<St> {}
    impl<St: State> State for SetAxis<St> {
        type Axis = Set<members::axis>;
        type Value = St::Value;
    }
    ///State transition - sets the `value` field to Set
    pub struct SetValue<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetValue<St> {}
    impl<St: State> State for SetValue<St> {
        type Axis = St::Axis;
        type Value = Set<members::value>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `axis` field
        pub struct axis(());
        ///Marker type for the `value` field
        pub struct value(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ResonanceValueBuilder<
    St: resonance_value_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl ResonanceValue<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ResonanceValueBuilder<resonance_value_state::Empty, DefaultStr> {
        ResonanceValueBuilder::new()
    }
}

impl<S: BosStr> ResonanceValue<S> {
    /// Create a new builder for this type
    pub fn builder() -> ResonanceValueBuilder<resonance_value_state::Empty, S> {
        ResonanceValueBuilder::builder()
    }
}

impl ResonanceValueBuilder<resonance_value_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ResonanceValueBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ResonanceValueBuilder<resonance_value_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ResonanceValueBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ResonanceValueBuilder<St, S>
where
    St: resonance_value_state::State,
    St::Axis: resonance_value_state::IsUnset,
{
    /// Set the `axis` field (required)
    pub fn axis(
        mut self,
        value: impl Into<S>,
    ) -> ResonanceValueBuilder<resonance_value_state::SetAxis<St>, S> {
        self._fields.0 = Option::Some(value.into());
        ResonanceValueBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ResonanceValueBuilder<St, S>
where
    St: resonance_value_state::State,
    St::Value: resonance_value_state::IsUnset,
{
    /// Set the `value` field (required)
    pub fn value(
        mut self,
        value: impl Into<i64>,
    ) -> ResonanceValueBuilder<resonance_value_state::SetValue<St>, S> {
        self._fields.1 = Option::Some(value.into());
        ResonanceValueBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ResonanceValueBuilder<St, S>
where
    St: resonance_value_state::State,
    St::Axis: resonance_value_state::IsSet,
    St::Value: resonance_value_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> ResonanceValue<S> {
        ResonanceValue {
            axis: self._fields.0.unwrap(),
            value: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> ResonanceValue<S> {
        ResonanceValue {
            axis: self._fields.0.unwrap(),
            value: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}