// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: at.telluri.node
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// A Node — a place where quintessence naturally gathers and springs forth. Source of raw quintessence (meditate) and the anchor where tass crystallizes (tassilize).

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "at.telluri.node",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Node<S: BosStr = DefaultStr> {
    ///Current quintessence in the ambient pool. Defaults to rating * 5 if unset (a fresh, full node).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ambient_quintessence: Option<i64>,
    ///Timestamp when this Node was minted
    pub created_at: Datetime,
    ///Freeform description — appearance, feel, history
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<S>,
    ///Where in the world this Node sits
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<S>,
    ///Display name for the Node
    pub name: S,
    ///Node background rating (1-5). Determines max quintessence capacity (rating * 5 by default).
    pub rating: i64,
    ///Resonance type (e.g. dynamic, static, primordial, pattern, questing)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resonance: Option<S>,
    ///Coincidental form tass naturally takes at this Node (e.g. 'a silver coin', 'a vial of ink')
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tass_form: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct NodeGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Node<S>,
}

impl<S: BosStr> Node<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, NodeRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct NodeRecord;
impl XrpcResp for NodeRecord {
    const NSID: &'static str = "at.telluri.node";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = NodeGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<NodeGetRecordOutput<S>> for Node<S> {
    fn from(output: NodeGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Node<S> {
    const NSID: &'static str = "at.telluri.node";
    type Record = NodeRecord;
}

impl Collection for NodeRecord {
    const NSID: &'static str = "at.telluri.node";
    type Record = NodeRecord;
}

impl<S: BosStr> LexiconSchema for Node<S> {
    fn nsid() -> &'static str {
        "at.telluri.node"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_at_telluri_node()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.ambient_quintessence {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("ambient_quintessence"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.description {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 2000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("description"),
                    max: 2000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.description {
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 1000usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("description"),
                        max: 1000usize,
                        actual: count,
                    });
                }
            }
        }
        if let Some(ref value) = self.location {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 500usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("location"),
                    max: 500usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.location {
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 250usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("location"),
                        max: 250usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.name;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 200usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("name"),
                    max: 200usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.name;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 100usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("name"),
                        max: 100usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.rating;
            if *value > 5i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("rating"),
                    max: 5i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.rating;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("rating"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.resonance {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 50usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("resonance"),
                    max: 50usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.tass_form {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 200usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("tass_form"),
                    max: 200usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod node_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Name;
        type Rating;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Name = Unset;
        type Rating = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Name = St::Name;
        type Rating = St::Rating;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetName<St> {}
    impl<St: State> State for SetName<St> {
        type CreatedAt = St::CreatedAt;
        type Name = Set<members::name>;
        type Rating = St::Rating;
    }
    ///State transition - sets the `rating` field to Set
    pub struct SetRating<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetRating<St> {}
    impl<St: State> State for SetRating<St> {
        type CreatedAt = St::CreatedAt;
        type Name = St::Name;
        type Rating = Set<members::rating>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `name` field
        pub struct name(());
        ///Marker type for the `rating` field
        pub struct rating(());
    }
}

/// Builder for constructing an instance of this type.
pub struct NodeBuilder<St: node_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<i64>,
        Option<Datetime>,
        Option<S>,
        Option<S>,
        Option<S>,
        Option<i64>,
        Option<S>,
        Option<S>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Node<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> NodeBuilder<node_state::Empty, DefaultStr> {
        NodeBuilder::new()
    }
}

impl<S: BosStr> Node<S> {
    /// Create a new builder for this type
    pub fn builder() -> NodeBuilder<node_state::Empty, S> {
        NodeBuilder::builder()
    }
}

impl NodeBuilder<node_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        NodeBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> NodeBuilder<node_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        NodeBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: node_state::State, S: BosStr> NodeBuilder<St, S> {
    /// Set the `ambientQuintessence` field (optional)
    pub fn ambient_quintessence(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `ambientQuintessence` field to an Option value (optional)
    pub fn maybe_ambient_quintessence(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> NodeBuilder<St, S>
where
    St: node_state::State,
    St::CreatedAt: node_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> NodeBuilder<node_state::SetCreatedAt<St>, S> {
        self._fields.1 = Option::Some(value.into());
        NodeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: node_state::State, S: BosStr> NodeBuilder<St, S> {
    /// Set the `description` field (optional)
    pub fn description(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `description` field to an Option value (optional)
    pub fn maybe_description(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: node_state::State, S: BosStr> NodeBuilder<St, S> {
    /// Set the `location` field (optional)
    pub fn location(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `location` field to an Option value (optional)
    pub fn maybe_location(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St, S: BosStr> NodeBuilder<St, S>
where
    St: node_state::State,
    St::Name: node_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<S>,
    ) -> NodeBuilder<node_state::SetName<St>, S> {
        self._fields.4 = Option::Some(value.into());
        NodeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> NodeBuilder<St, S>
where
    St: node_state::State,
    St::Rating: node_state::IsUnset,
{
    /// Set the `rating` field (required)
    pub fn rating(
        mut self,
        value: impl Into<i64>,
    ) -> NodeBuilder<node_state::SetRating<St>, S> {
        self._fields.5 = Option::Some(value.into());
        NodeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: node_state::State, S: BosStr> NodeBuilder<St, S> {
    /// Set the `resonance` field (optional)
    pub fn resonance(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `resonance` field to an Option value (optional)
    pub fn maybe_resonance(mut self, value: Option<S>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St: node_state::State, S: BosStr> NodeBuilder<St, S> {
    /// Set the `tassForm` field (optional)
    pub fn tass_form(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.7 = value.into();
        self
    }
    /// Set the `tassForm` field to an Option value (optional)
    pub fn maybe_tass_form(mut self, value: Option<S>) -> Self {
        self._fields.7 = value;
        self
    }
}

impl<St, S: BosStr> NodeBuilder<St, S>
where
    St: node_state::State,
    St::CreatedAt: node_state::IsSet,
    St::Name: node_state::IsSet,
    St::Rating: node_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Node<S> {
        Node {
            ambient_quintessence: self._fields.0,
            created_at: self._fields.1.unwrap(),
            description: self._fields.2,
            location: self._fields.3,
            name: self._fields.4.unwrap(),
            rating: self._fields.5.unwrap(),
            resonance: self._fields.6,
            tass_form: self._fields.7,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Node<S> {
        Node {
            ambient_quintessence: self._fields.0,
            created_at: self._fields.1.unwrap(),
            description: self._fields.2,
            location: self._fields.3,
            name: self._fields.4.unwrap(),
            rating: self._fields.5.unwrap(),
            resonance: self._fields.6,
            tass_form: self._fields.7,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_at_telluri_node() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("at.telluri.node"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A Node — a place where quintessence naturally gathers and springs forth. Source of raw quintessence (meditate) and the anchor where tass crystallizes (tassilize).",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("name"), SmolStr::new_static("rating"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("ambientQuintessence"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Timestamp when this Node was minted"),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("description"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Freeform description — appearance, feel, history",
                                        ),
                                    ),
                                    max_length: Some(2000usize),
                                    max_graphemes: Some(1000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("location"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Where in the world this Node sits"),
                                    ),
                                    max_length: Some(500usize),
                                    max_graphemes: Some(250usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("name"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Display name for the Node"),
                                    ),
                                    max_length: Some(200usize),
                                    max_graphemes: Some(100usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("rating"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(1i64),
                                    maximum: Some(5i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("resonance"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Resonance type (e.g. dynamic, static, primordial, pattern, questing)",
                                        ),
                                    ),
                                    max_length: Some(50usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("tassForm"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Coincidental form tass naturally takes at this Node (e.g. 'a silver coin', 'a vial of ink')",
                                        ),
                                    ),
                                    max_length: Some(200usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}