// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `at.telluri` Lexicon namespace/module.
pub mod act;
pub mod node;
pub mod resonance;