// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: at.telluri.act.tassilize
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// Genesis record: quintessence crystallized into Tass at a Node. Captures the initial energy endowment of a tass object at the moment of its formation. Forms the anchor that enervate records drain against.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "at.telluri.act.tassilize",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Tassilize<S: BosStr = DefaultStr> {
    ///Timestamp when this tass was crystallized
    pub created_at: Datetime,
    ///Coincidental form the tass takes in reality (e.g. 'a silver coin', 'a vial of ink')
    #[serde(skip_serializing_if = "Option::is_none")]
    pub form: Option<S>,
    ///AT-URI of the Node where this tass formed (e.g. at://did:plc:.../at.telluri.node/rkey)
    pub node: AtUri<S>,
    ///Freeform note about the tassilization
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<S>,
    ///Initial quintessence value crystallized into this tass
    pub quintessence: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct TassilizeGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Tassilize<S>,
}

impl<S: BosStr> Tassilize<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, TassilizeRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct TassilizeRecord;
impl XrpcResp for TassilizeRecord {
    const NSID: &'static str = "at.telluri.act.tassilize";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = TassilizeGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<TassilizeGetRecordOutput<S>> for Tassilize<S> {
    fn from(output: TassilizeGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Tassilize<S> {
    const NSID: &'static str = "at.telluri.act.tassilize";
    type Record = TassilizeRecord;
}

impl Collection for TassilizeRecord {
    const NSID: &'static str = "at.telluri.act.tassilize";
    type Record = TassilizeRecord;
}

impl<S: BosStr> LexiconSchema for Tassilize<S> {
    fn nsid() -> &'static str {
        "at.telluri.act.tassilize"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_at_telluri_act_tassilize()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.form {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 200usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("form"),
                    max: 200usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.form {
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 100usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("form"),
                        max: 100usize,
                        actual: count,
                    });
                }
            }
        }
        if let Some(ref value) = self.note {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 2000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("note"),
                    max: 2000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.note {
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 1000usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("note"),
                        max: 1000usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.quintessence;
            if *value > 100i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("quintessence"),
                    max: 100i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.quintessence;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("quintessence"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod tassilize_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Node;
        type Quintessence;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Node = Unset;
        type Quintessence = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Node = St::Node;
        type Quintessence = St::Quintessence;
    }
    ///State transition - sets the `node` field to Set
    pub struct SetNode<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetNode<St> {}
    impl<St: State> State for SetNode<St> {
        type CreatedAt = St::CreatedAt;
        type Node = Set<members::node>;
        type Quintessence = St::Quintessence;
    }
    ///State transition - sets the `quintessence` field to Set
    pub struct SetQuintessence<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetQuintessence<St> {}
    impl<St: State> State for SetQuintessence<St> {
        type CreatedAt = St::CreatedAt;
        type Node = St::Node;
        type Quintessence = Set<members::quintessence>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `node` field
        pub struct node(());
        ///Marker type for the `quintessence` field
        pub struct quintessence(());
    }
}

/// Builder for constructing an instance of this type.
pub struct TassilizeBuilder<St: tassilize_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Datetime>, Option<S>, Option<AtUri<S>>, Option<S>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl Tassilize<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> TassilizeBuilder<tassilize_state::Empty, DefaultStr> {
        TassilizeBuilder::new()
    }
}

impl<S: BosStr> Tassilize<S> {
    /// Create a new builder for this type
    pub fn builder() -> TassilizeBuilder<tassilize_state::Empty, S> {
        TassilizeBuilder::builder()
    }
}

impl TassilizeBuilder<tassilize_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        TassilizeBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> TassilizeBuilder<tassilize_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        TassilizeBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> TassilizeBuilder<St, S>
where
    St: tassilize_state::State,
    St::CreatedAt: tassilize_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> TassilizeBuilder<tassilize_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        TassilizeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: tassilize_state::State, S: BosStr> TassilizeBuilder<St, S> {
    /// Set the `form` field (optional)
    pub fn form(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `form` field to an Option value (optional)
    pub fn maybe_form(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> TassilizeBuilder<St, S>
where
    St: tassilize_state::State,
    St::Node: tassilize_state::IsUnset,
{
    /// Set the `node` field (required)
    pub fn node(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> TassilizeBuilder<tassilize_state::SetNode<St>, S> {
        self._fields.2 = Option::Some(value.into());
        TassilizeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: tassilize_state::State, S: BosStr> TassilizeBuilder<St, S> {
    /// Set the `note` field (optional)
    pub fn note(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `note` field to an Option value (optional)
    pub fn maybe_note(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St, S: BosStr> TassilizeBuilder<St, S>
where
    St: tassilize_state::State,
    St::Quintessence: tassilize_state::IsUnset,
{
    /// Set the `quintessence` field (required)
    pub fn quintessence(
        mut self,
        value: impl Into<i64>,
    ) -> TassilizeBuilder<tassilize_state::SetQuintessence<St>, S> {
        self._fields.4 = Option::Some(value.into());
        TassilizeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> TassilizeBuilder<St, S>
where
    St: tassilize_state::State,
    St::CreatedAt: tassilize_state::IsSet,
    St::Node: tassilize_state::IsSet,
    St::Quintessence: tassilize_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Tassilize<S> {
        Tassilize {
            created_at: self._fields.0.unwrap(),
            form: self._fields.1,
            node: self._fields.2.unwrap(),
            note: self._fields.3,
            quintessence: self._fields.4.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> Tassilize<S> {
        Tassilize {
            created_at: self._fields.0.unwrap(),
            form: self._fields.1,
            node: self._fields.2.unwrap(),
            note: self._fields.3,
            quintessence: self._fields.4.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_at_telluri_act_tassilize() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("at.telluri.act.tassilize"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Genesis record: quintessence crystallized into Tass at a Node. Captures the initial energy endowment of a tass object at the moment of its formation. Forms the anchor that enervate records drain against.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("node"),
                                SmolStr::new_static("quintessence"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Timestamp when this tass was crystallized",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("form"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Coincidental form the tass takes in reality (e.g. 'a silver coin', 'a vial of ink')",
                                        ),
                                    ),
                                    max_length: Some(200usize),
                                    max_graphemes: Some(100usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("node"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "AT-URI of the Node where this tass formed (e.g. at://did:plc:.../at.telluri.node/rkey)",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::AtUri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("note"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Freeform note about the tassilization"),
                                    ),
                                    max_length: Some(2000usize),
                                    max_graphemes: Some(1000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("quintessence"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(100i64),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}