// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: equipment.rpg.give
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{Did, AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// Records that a provider granted an item to a specific recipient. The asset blob is not stored here — only the CID for integrity verification. Each give record is one item to one recipient.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "equipment.rpg.give",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Give<S: BosStr = DefaultStr> {
    ///CID of the canonical asset or icon PNG. Used to verify the player's copy is untampered.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_cid: Option<S>,
    ///Generator layer category for 'layer' items (e.g. 'tops', 'righthand'). Omit for 'inventory' items.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<S>,
    ///Origin description — where and how the item was earned (e.g. 'Avonlea Theatre popcorn vendor').
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<S>,
    ///Flavour text or description of the item.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<S>,
    ///When this item was given.
    pub given_at: Datetime,
    ///CID of the item's icon PNG, if distinct from the asset.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon_cid: Option<S>,
    ///Unique item identifier (e.g. 'popcorn', 'theatre_shirt').
    pub item: S,
    ///Item kind. 'layer' for sprite-generator wearables (held/overlay are subtypes). For non-wearable inventory items, any descriptive string such as 'badge', 'potion', 'map', 'key', 'ticket', etc. Defaults to 'layer' if omitted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<S>,
    ///DID of the player who received this item.
    pub recipient: Did<S>,
    ///Provider-defined properties or metadata for the item.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stats: Option<Data<S>>,
    ///Human-readable display name for the item.
    pub title: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Provider-defined properties or metadata for the item.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GiveStats<S: BosStr = DefaultStr> {
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GiveGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Give<S>,
}

impl<S: BosStr> Give<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, GiveRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct GiveRecord;
impl XrpcResp for GiveRecord {
    const NSID: &'static str = "equipment.rpg.give";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GiveGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<GiveGetRecordOutput<S>> for Give<S> {
    fn from(output: GiveGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Give<S> {
    const NSID: &'static str = "equipment.rpg.give";
    type Record = GiveRecord;
}

impl Collection for GiveRecord {
    const NSID: &'static str = "equipment.rpg.give";
    type Record = GiveRecord;
}

impl<S: BosStr> LexiconSchema for Give<S> {
    fn nsid() -> &'static str {
        "equipment.rpg.give"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_equipment_rpg_give()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.asset_cid {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 200usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("asset_cid"),
                    max: 200usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.category {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 30usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("category"),
                    max: 30usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.context {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 200usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("context"),
                    max: 200usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.description {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 500usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("description"),
                    max: 500usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.icon_cid {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 200usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("icon_cid"),
                    max: 200usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.item;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 50usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("item"),
                    max: 50usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.kind {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 20usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("kind"),
                    max: 20usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.title;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 100usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("title"),
                    max: 100usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for GiveStats<S> {
    fn nsid() -> &'static str {
        "equipment.rpg.give"
    }
    fn def_name() -> &'static str {
        "GiveStats"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_equipment_rpg_give()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_equipment_rpg_give() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("equipment.rpg.give"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Records that a provider granted an item to a specific recipient. The asset blob is not stored here — only the CID for integrity verification. Each give record is one item to one recipient.",
                        ),
                    ),
                    key: Some(CowStr::new_static("any")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("recipient"),
                                SmolStr::new_static("item"), SmolStr::new_static("title"),
                                SmolStr::new_static("givenAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("assetCid"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "CID of the canonical asset or icon PNG. Used to verify the player's copy is untampered.",
                                        ),
                                    ),
                                    max_length: Some(200usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("category"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Generator layer category for 'layer' items (e.g. 'tops', 'righthand'). Omit for 'inventory' items.",
                                        ),
                                    ),
                                    max_length: Some(30usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("context"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Origin description — where and how the item was earned (e.g. 'Avonlea Theatre popcorn vendor').",
                                        ),
                                    ),
                                    max_length: Some(200usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("description"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Flavour text or description of the item.",
                                        ),
                                    ),
                                    max_length: Some(500usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("givenAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("When this item was given."),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("iconCid"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "CID of the item's icon PNG, if distinct from the asset.",
                                        ),
                                    ),
                                    max_length: Some(200usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("item"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Unique item identifier (e.g. 'popcorn', 'theatre_shirt').",
                                        ),
                                    ),
                                    max_length: Some(50usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("kind"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Item kind. 'layer' for sprite-generator wearables (held/overlay are subtypes). For non-wearable inventory items, any descriptive string such as 'badge', 'potion', 'map', 'key', 'ticket', etc. Defaults to 'layer' if omitted.",
                                        ),
                                    ),
                                    max_length: Some(20usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("recipient"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "DID of the player who received this item.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Did),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("stats"),
                                LexObjectProperty::Object(LexObject {
                                    description: Some(
                                        CowStr::new_static(
                                            "Provider-defined properties or metadata for the item.",
                                        ),
                                    ),
                                    properties: {
                                        #[allow(unused_mut)]
                                        let mut map = BTreeMap::new();
                                        map
                                    },
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("title"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Human-readable display name for the item.",
                                        ),
                                    ),
                                    max_length: Some(100usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod give_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type GivenAt;
        type Item;
        type Recipient;
        type Title;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type GivenAt = Unset;
        type Item = Unset;
        type Recipient = Unset;
        type Title = Unset;
    }
    ///State transition - sets the `given_at` field to Set
    pub struct SetGivenAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetGivenAt<St> {}
    impl<St: State> State for SetGivenAt<St> {
        type GivenAt = Set<members::given_at>;
        type Item = St::Item;
        type Recipient = St::Recipient;
        type Title = St::Title;
    }
    ///State transition - sets the `item` field to Set
    pub struct SetItem<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetItem<St> {}
    impl<St: State> State for SetItem<St> {
        type GivenAt = St::GivenAt;
        type Item = Set<members::item>;
        type Recipient = St::Recipient;
        type Title = St::Title;
    }
    ///State transition - sets the `recipient` field to Set
    pub struct SetRecipient<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetRecipient<St> {}
    impl<St: State> State for SetRecipient<St> {
        type GivenAt = St::GivenAt;
        type Item = St::Item;
        type Recipient = Set<members::recipient>;
        type Title = St::Title;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTitle<St> {}
    impl<St: State> State for SetTitle<St> {
        type GivenAt = St::GivenAt;
        type Item = St::Item;
        type Recipient = St::Recipient;
        type Title = Set<members::title>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `given_at` field
        pub struct given_at(());
        ///Marker type for the `item` field
        pub struct item(());
        ///Marker type for the `recipient` field
        pub struct recipient(());
        ///Marker type for the `title` field
        pub struct title(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GiveBuilder<St: give_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<S>,
        Option<S>,
        Option<S>,
        Option<Datetime>,
        Option<S>,
        Option<S>,
        Option<S>,
        Option<Did<S>>,
        Option<Data<S>>,
        Option<S>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Give<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GiveBuilder<give_state::Empty, DefaultStr> {
        GiveBuilder::new()
    }
}

impl<S: BosStr> Give<S> {
    /// Create a new builder for this type
    pub fn builder() -> GiveBuilder<give_state::Empty, S> {
        GiveBuilder::builder()
    }
}

impl GiveBuilder<give_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GiveBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GiveBuilder<give_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GiveBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: give_state::State, S: BosStr> GiveBuilder<St, S> {
    /// Set the `assetCid` field (optional)
    pub fn asset_cid(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `assetCid` field to an Option value (optional)
    pub fn maybe_asset_cid(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: give_state::State, S: BosStr> GiveBuilder<St, S> {
    /// Set the `category` field (optional)
    pub fn category(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `category` field to an Option value (optional)
    pub fn maybe_category(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: give_state::State, S: BosStr> GiveBuilder<St, S> {
    /// Set the `context` field (optional)
    pub fn context(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `context` field to an Option value (optional)
    pub fn maybe_context(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: give_state::State, S: BosStr> GiveBuilder<St, S> {
    /// Set the `description` field (optional)
    pub fn description(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `description` field to an Option value (optional)
    pub fn maybe_description(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St, S: BosStr> GiveBuilder<St, S>
where
    St: give_state::State,
    St::GivenAt: give_state::IsUnset,
{
    /// Set the `givenAt` field (required)
    pub fn given_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> GiveBuilder<give_state::SetGivenAt<St>, S> {
        self._fields.4 = Option::Some(value.into());
        GiveBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: give_state::State, S: BosStr> GiveBuilder<St, S> {
    /// Set the `iconCid` field (optional)
    pub fn icon_cid(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `iconCid` field to an Option value (optional)
    pub fn maybe_icon_cid(mut self, value: Option<S>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St, S: BosStr> GiveBuilder<St, S>
where
    St: give_state::State,
    St::Item: give_state::IsUnset,
{
    /// Set the `item` field (required)
    pub fn item(
        mut self,
        value: impl Into<S>,
    ) -> GiveBuilder<give_state::SetItem<St>, S> {
        self._fields.6 = Option::Some(value.into());
        GiveBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: give_state::State, S: BosStr> GiveBuilder<St, S> {
    /// Set the `kind` field (optional)
    pub fn kind(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.7 = value.into();
        self
    }
    /// Set the `kind` field to an Option value (optional)
    pub fn maybe_kind(mut self, value: Option<S>) -> Self {
        self._fields.7 = value;
        self
    }
}

impl<St, S: BosStr> GiveBuilder<St, S>
where
    St: give_state::State,
    St::Recipient: give_state::IsUnset,
{
    /// Set the `recipient` field (required)
    pub fn recipient(
        mut self,
        value: impl Into<Did<S>>,
    ) -> GiveBuilder<give_state::SetRecipient<St>, S> {
        self._fields.8 = Option::Some(value.into());
        GiveBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: give_state::State, S: BosStr> GiveBuilder<St, S> {
    /// Set the `stats` field (optional)
    pub fn stats(mut self, value: impl Into<Option<Data<S>>>) -> Self {
        self._fields.9 = value.into();
        self
    }
    /// Set the `stats` field to an Option value (optional)
    pub fn maybe_stats(mut self, value: Option<Data<S>>) -> Self {
        self._fields.9 = value;
        self
    }
}

impl<St, S: BosStr> GiveBuilder<St, S>
where
    St: give_state::State,
    St::Title: give_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(
        mut self,
        value: impl Into<S>,
    ) -> GiveBuilder<give_state::SetTitle<St>, S> {
        self._fields.10 = Option::Some(value.into());
        GiveBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GiveBuilder<St, S>
where
    St: give_state::State,
    St::GivenAt: give_state::IsSet,
    St::Item: give_state::IsSet,
    St::Recipient: give_state::IsSet,
    St::Title: give_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Give<S> {
        Give {
            asset_cid: self._fields.0,
            category: self._fields.1,
            context: self._fields.2,
            description: self._fields.3,
            given_at: self._fields.4.unwrap(),
            icon_cid: self._fields.5,
            item: self._fields.6.unwrap(),
            kind: self._fields.7,
            recipient: self._fields.8.unwrap(),
            stats: self._fields.9,
            title: self._fields.10.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Give<S> {
        Give {
            asset_cid: self._fields.0,
            category: self._fields.1,
            context: self._fields.2,
            description: self._fields.3,
            given_at: self._fields.4.unwrap(),
            icon_cid: self._fields.5,
            item: self._fields.6.unwrap(),
            kind: self._fields.7,
            recipient: self._fields.8.unwrap(),
            stats: self._fields.9,
            title: self._fields.10.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}