// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: equipment.rpg.item
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::blob::BlobRef;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{Did, AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// An item in the player's inventory. Self-contained with all data needed for rendering and display. The give URI and assetCid enable verification against the provider's attestation. Each record is one item.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "equipment.rpg.item",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Item<S: BosStr = DefaultStr> {
    ///When the player accepted this item.
    pub accepted_at: Datetime,
    ///The item's sprite layer artwork (144x192 PNG). Required for 'layer' items, optional for 'inventory' items.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset: Option<BlobRef<S>>,
    ///CID of the canonical asset or icon blob. Must match the give record's assetCid for verification.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_cid: Option<S>,
    ///Sprite-sheet row indices (0-3) where this layer composites behind the body via destination-over blending. Row 0=down, 1=left, 2=right, 3=up. Omit for normal source-over on all rows.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub behind_rows: Option<Vec<i64>>,
    ///Generator layer category for 'layer' items (e.g. 'tops', 'righthand'). Ignored for 'inventory' items.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<S>,
    ///Color channels defined by this item's colorway. Each entry names a recolorable region and declares its sentinel color and optional default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channels: Option<Vec<Data<S>>>,
    ///Colorway map (_c) for the asset. A 144x192 PNG with sentinel-colored pixels indicating recolorable regions. Required for 'layer' items that support recoloring.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub colorway: Option<BlobRef<S>>,
    ///Origin description copied from the give record.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<S>,
    ///Flavour text or description.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<S>,
    ///Fit-class tag for this item (format <category>.<name>) used by class-based suppression.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fit_class: Option<S>,
    ///AT URI of the equipment.rpg.give record on the provider's PDS.
    pub give: AtUri<S>,
    ///Small standalone icon for the item (e.g. 64x64 PNG). Used in inventory displays and profile panels.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<BlobRef<S>>,
    ///Item identifier matching the give record (e.g. 'popcorn', 'theatre_shirt').
    pub item: S,
    ///Item kind. 'layer' for sprite-generator wearables (requires category + asset). For non-wearable inventory items, use any descriptive type string such as 'badge', 'potion', 'map', 'key', 'ticket', etc. This value is shown as the item's type label in the player's inventory. Defaults to 'layer' if omitted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<S>,
    ///DID of the provider who gave this item.
    pub provider: Did<S>,
    ///Item properties copied from the give record at acceptance time.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stats: Option<Data<S>>,
    ///When this item is suppressed, render this same-category item name instead (e.g. replace pigtails with basic short).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suppress_as: Option<S>,
    ///Fit-class identifiers that should be hidden while this item is equipped (e.g. hide all items tagged hair.*).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suppress_classes: Option<Vec<S>>,
    ///Layer IDs that should be hidden while this item is equipped (e.g. a hat suppressing hair and bangs).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suppress_layers: Option<Vec<S>>,
    ///Display name for the item.
    pub title: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Item properties copied from the give record at acceptance time.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ItemStats<S: BosStr = DefaultStr> {
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ItemGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Item<S>,
}

impl<S: BosStr> Item<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, ItemRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct ItemRecord;
impl XrpcResp for ItemRecord {
    const NSID: &'static str = "equipment.rpg.item";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ItemGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<ItemGetRecordOutput<S>> for Item<S> {
    fn from(output: ItemGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Item<S> {
    const NSID: &'static str = "equipment.rpg.item";
    type Record = ItemRecord;
}

impl Collection for ItemRecord {
    const NSID: &'static str = "equipment.rpg.item";
    type Record = ItemRecord;
}

impl<S: BosStr> LexiconSchema for Item<S> {
    fn nsid() -> &'static str {
        "equipment.rpg.item"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_equipment_rpg_item()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.asset {
            {
                let mime = value.blob().mime_type.as_str();
                let accepted: &[&str] = &["image/png"];
                let matched = accepted
                    .iter()
                    .any(|pattern| {
                        if *pattern == "*/*" {
                            true
                        } else if pattern.ends_with("/*") {
                            let prefix = &pattern[..pattern.len() - 2];
                            mime.starts_with(prefix)
                                && mime.as_bytes().get(prefix.len()) == Some(&b'/')
                        } else {
                            mime == *pattern
                        }
                    });
                if !matched {
                    return Err(ConstraintError::BlobMimeTypeNotAccepted {
                        path: ValidationPath::from_field("asset"),
                        accepted: vec!["image/png".to_string()],
                        actual: mime.to_string(),
                    });
                }
            }
        }
        if let Some(ref value) = self.asset_cid {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 200usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("asset_cid"),
                    max: 200usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.behind_rows {
            #[allow(unused_comparisons)]
            if value.len() > 4usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("behind_rows"),
                    max: 4usize,
                    actual: value.len(),
                });
            }
        }
        if let Some(ref value) = self.category {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 30usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("category"),
                    max: 30usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.channels {
            #[allow(unused_comparisons)]
            if value.len() > 8usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("channels"),
                    max: 8usize,
                    actual: value.len(),
                });
            }
        }
        if let Some(ref value) = self.colorway {
            {
                let mime = value.blob().mime_type.as_str();
                let accepted: &[&str] = &["image/png"];
                let matched = accepted
                    .iter()
                    .any(|pattern| {
                        if *pattern == "*/*" {
                            true
                        } else if pattern.ends_with("/*") {
                            let prefix = &pattern[..pattern.len() - 2];
                            mime.starts_with(prefix)
                                && mime.as_bytes().get(prefix.len()) == Some(&b'/')
                        } else {
                            mime == *pattern
                        }
                    });
                if !matched {
                    return Err(ConstraintError::BlobMimeTypeNotAccepted {
                        path: ValidationPath::from_field("colorway"),
                        accepted: vec!["image/png".to_string()],
                        actual: mime.to_string(),
                    });
                }
            }
        }
        if let Some(ref value) = self.context {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 200usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("context"),
                    max: 200usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.description {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 500usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("description"),
                    max: 500usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.fit_class {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 90usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("fit_class"),
                    max: 90usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.icon {
            {
                let mime = value.blob().mime_type.as_str();
                let accepted: &[&str] = &["image/png"];
                let matched = accepted
                    .iter()
                    .any(|pattern| {
                        if *pattern == "*/*" {
                            true
                        } else if pattern.ends_with("/*") {
                            let prefix = &pattern[..pattern.len() - 2];
                            mime.starts_with(prefix)
                                && mime.as_bytes().get(prefix.len()) == Some(&b'/')
                        } else {
                            mime == *pattern
                        }
                    });
                if !matched {
                    return Err(ConstraintError::BlobMimeTypeNotAccepted {
                        path: ValidationPath::from_field("icon"),
                        accepted: vec!["image/png".to_string()],
                        actual: mime.to_string(),
                    });
                }
            }
        }
        {
            let value = &self.item;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 50usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("item"),
                    max: 50usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.kind {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 20usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("kind"),
                    max: 20usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.suppress_as {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 120usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("suppress_as"),
                    max: 120usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.suppress_classes {
            #[allow(unused_comparisons)]
            if value.len() > 20usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("suppress_classes"),
                    max: 20usize,
                    actual: value.len(),
                });
            }
        }
        if let Some(ref value) = self.suppress_layers {
            #[allow(unused_comparisons)]
            if value.len() > 20usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("suppress_layers"),
                    max: 20usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.title;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 100usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("title"),
                    max: 100usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for ItemStats<S> {
    fn nsid() -> &'static str {
        "equipment.rpg.item"
    }
    fn def_name() -> &'static str {
        "ItemStats"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_equipment_rpg_item()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_equipment_rpg_item() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("equipment.rpg.item"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "An item in the player's inventory. Self-contained with all data needed for rendering and display. The give URI and assetCid enable verification against the provider's attestation. Each record is one item.",
                        ),
                    ),
                    key: Some(CowStr::new_static("any")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("item"), SmolStr::new_static("title"),
                                SmolStr::new_static("give"),
                                SmolStr::new_static("provider"),
                                SmolStr::new_static("acceptedAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("acceptedAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("When the player accepted this item."),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("asset"),
                                LexObjectProperty::Blob(LexBlob { ..Default::default() }),
                            );
                            map.insert(
                                SmolStr::new_static("assetCid"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "CID of the canonical asset or icon blob. Must match the give record's assetCid for verification.",
                                        ),
                                    ),
                                    max_length: Some(200usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("behindRows"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Sprite-sheet row indices (0-3) where this layer composites behind the body via destination-over blending. Row 0=down, 1=left, 2=right, 3=up. Omit for normal source-over on all rows.",
                                        ),
                                    ),
                                    items: LexArrayItem::Integer(LexInteger {
                                        ..Default::default()
                                    }),
                                    max_length: Some(4usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("category"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Generator layer category for 'layer' items (e.g. 'tops', 'righthand'). Ignored for 'inventory' items.",
                                        ),
                                    ),
                                    max_length: Some(30usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("channels"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Color channels defined by this item's colorway. Each entry names a recolorable region and declares its sentinel color and optional default.",
                                        ),
                                    ),
                                    items: LexArrayItem::Object(LexObject {
                                        required: Some(
                                            vec![
                                                SmolStr::new_static("name"), SmolStr::new_static("color")
                                            ],
                                        ),
                                        properties: {
                                            #[allow(unused_mut)]
                                            let mut map = BTreeMap::new();
                                            map.insert(
                                                SmolStr::new_static("color"),
                                                LexObjectProperty::String(LexString {
                                                    description: Some(
                                                        CowStr::new_static(
                                                            "Sentinel hex color in the colorway map for this channel (e.g. '#0000FF' for blue).",
                                                        ),
                                                    ),
                                                    max_length: Some(7usize),
                                                    ..Default::default()
                                                }),
                                            );
                                            map.insert(
                                                SmolStr::new_static("defaultColor"),
                                                LexObjectProperty::String(LexString {
                                                    description: Some(
                                                        CowStr::new_static(
                                                            "Suggested default hex color for this channel in the player's color picker.",
                                                        ),
                                                    ),
                                                    max_length: Some(7usize),
                                                    ..Default::default()
                                                }),
                                            );
                                            map.insert(
                                                SmolStr::new_static("name"),
                                                LexObjectProperty::String(LexString {
                                                    description: Some(
                                                        CowStr::new_static(
                                                            "Channel identifier (e.g. 'main', 'sub1', 'brim', 'ribbon').",
                                                        ),
                                                    ),
                                                    max_length: Some(20usize),
                                                    ..Default::default()
                                                }),
                                            );
                                            map
                                        },
                                        ..Default::default()
                                    }),
                                    max_length: Some(8usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("colorway"),
                                LexObjectProperty::Blob(LexBlob { ..Default::default() }),
                            );
                            map.insert(
                                SmolStr::new_static("context"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Origin description copied from the give record.",
                                        ),
                                    ),
                                    max_length: Some(200usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("description"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Flavour text or description."),
                                    ),
                                    max_length: Some(500usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("fitClass"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Fit-class tag for this item (format <category>.<name>) used by class-based suppression.",
                                        ),
                                    ),
                                    max_length: Some(90usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("give"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "AT URI of the equipment.rpg.give record on the provider's PDS.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::AtUri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("icon"),
                                LexObjectProperty::Blob(LexBlob { ..Default::default() }),
                            );
                            map.insert(
                                SmolStr::new_static("item"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Item identifier matching the give record (e.g. 'popcorn', 'theatre_shirt').",
                                        ),
                                    ),
                                    max_length: Some(50usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("kind"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Item kind. 'layer' for sprite-generator wearables (requires category + asset). For non-wearable inventory items, use any descriptive type string such as 'badge', 'potion', 'map', 'key', 'ticket', etc. This value is shown as the item's type label in the player's inventory. Defaults to 'layer' if omitted.",
                                        ),
                                    ),
                                    max_length: Some(20usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("provider"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "DID of the provider who gave this item.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Did),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("stats"),
                                LexObjectProperty::Object(LexObject {
                                    description: Some(
                                        CowStr::new_static(
                                            "Item properties copied from the give record at acceptance time.",
                                        ),
                                    ),
                                    properties: {
                                        #[allow(unused_mut)]
                                        let mut map = BTreeMap::new();
                                        map
                                    },
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("suppressAs"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "When this item is suppressed, render this same-category item name instead (e.g. replace pigtails with basic short).",
                                        ),
                                    ),
                                    max_length: Some(120usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("suppressClasses"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Fit-class identifiers that should be hidden while this item is equipped (e.g. hide all items tagged hair.*).",
                                        ),
                                    ),
                                    items: LexArrayItem::String(LexString {
                                        max_length: Some(90usize),
                                        ..Default::default()
                                    }),
                                    max_length: Some(20usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("suppressLayers"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Layer IDs that should be hidden while this item is equipped (e.g. a hat suppressing hair and bangs).",
                                        ),
                                    ),
                                    items: LexArrayItem::String(LexString {
                                        max_length: Some(30usize),
                                        ..Default::default()
                                    }),
                                    max_length: Some(20usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("title"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Display name for the item."),
                                    ),
                                    max_length: Some(100usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod item_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type AcceptedAt;
        type Give;
        type Item;
        type Provider;
        type Title;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type AcceptedAt = Unset;
        type Give = Unset;
        type Item = Unset;
        type Provider = Unset;
        type Title = Unset;
    }
    ///State transition - sets the `accepted_at` field to Set
    pub struct SetAcceptedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetAcceptedAt<St> {}
    impl<St: State> State for SetAcceptedAt<St> {
        type AcceptedAt = Set<members::accepted_at>;
        type Give = St::Give;
        type Item = St::Item;
        type Provider = St::Provider;
        type Title = St::Title;
    }
    ///State transition - sets the `give` field to Set
    pub struct SetGive<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetGive<St> {}
    impl<St: State> State for SetGive<St> {
        type AcceptedAt = St::AcceptedAt;
        type Give = Set<members::give>;
        type Item = St::Item;
        type Provider = St::Provider;
        type Title = St::Title;
    }
    ///State transition - sets the `item` field to Set
    pub struct SetItem<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetItem<St> {}
    impl<St: State> State for SetItem<St> {
        type AcceptedAt = St::AcceptedAt;
        type Give = St::Give;
        type Item = Set<members::item>;
        type Provider = St::Provider;
        type Title = St::Title;
    }
    ///State transition - sets the `provider` field to Set
    pub struct SetProvider<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetProvider<St> {}
    impl<St: State> State for SetProvider<St> {
        type AcceptedAt = St::AcceptedAt;
        type Give = St::Give;
        type Item = St::Item;
        type Provider = Set<members::provider>;
        type Title = St::Title;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTitle<St> {}
    impl<St: State> State for SetTitle<St> {
        type AcceptedAt = St::AcceptedAt;
        type Give = St::Give;
        type Item = St::Item;
        type Provider = St::Provider;
        type Title = Set<members::title>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `accepted_at` field
        pub struct accepted_at(());
        ///Marker type for the `give` field
        pub struct give(());
        ///Marker type for the `item` field
        pub struct item(());
        ///Marker type for the `provider` field
        pub struct provider(());
        ///Marker type for the `title` field
        pub struct title(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ItemBuilder<St: item_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Datetime>,
        Option<BlobRef<S>>,
        Option<S>,
        Option<Vec<i64>>,
        Option<S>,
        Option<Vec<Data<S>>>,
        Option<BlobRef<S>>,
        Option<S>,
        Option<S>,
        Option<S>,
        Option<AtUri<S>>,
        Option<BlobRef<S>>,
        Option<S>,
        Option<S>,
        Option<Did<S>>,
        Option<Data<S>>,
        Option<S>,
        Option<Vec<S>>,
        Option<Vec<S>>,
        Option<S>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Item<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ItemBuilder<item_state::Empty, DefaultStr> {
        ItemBuilder::new()
    }
}

impl<S: BosStr> Item<S> {
    /// Create a new builder for this type
    pub fn builder() -> ItemBuilder<item_state::Empty, S> {
        ItemBuilder::builder()
    }
}

impl ItemBuilder<item_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ItemBuilder {
            _state: PhantomData,
            _fields: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ItemBuilder<item_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ItemBuilder {
            _state: PhantomData,
            _fields: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ItemBuilder<St, S>
where
    St: item_state::State,
    St::AcceptedAt: item_state::IsUnset,
{
    /// Set the `acceptedAt` field (required)
    pub fn accepted_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> ItemBuilder<item_state::SetAcceptedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        ItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `asset` field (optional)
    pub fn asset(mut self, value: impl Into<Option<BlobRef<S>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `asset` field to an Option value (optional)
    pub fn maybe_asset(mut self, value: Option<BlobRef<S>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `assetCid` field (optional)
    pub fn asset_cid(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `assetCid` field to an Option value (optional)
    pub fn maybe_asset_cid(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `behindRows` field (optional)
    pub fn behind_rows(mut self, value: impl Into<Option<Vec<i64>>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `behindRows` field to an Option value (optional)
    pub fn maybe_behind_rows(mut self, value: Option<Vec<i64>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `category` field (optional)
    pub fn category(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `category` field to an Option value (optional)
    pub fn maybe_category(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `channels` field (optional)
    pub fn channels(mut self, value: impl Into<Option<Vec<Data<S>>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `channels` field to an Option value (optional)
    pub fn maybe_channels(mut self, value: Option<Vec<Data<S>>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `colorway` field (optional)
    pub fn colorway(mut self, value: impl Into<Option<BlobRef<S>>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `colorway` field to an Option value (optional)
    pub fn maybe_colorway(mut self, value: Option<BlobRef<S>>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `context` field (optional)
    pub fn context(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.7 = value.into();
        self
    }
    /// Set the `context` field to an Option value (optional)
    pub fn maybe_context(mut self, value: Option<S>) -> Self {
        self._fields.7 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `description` field (optional)
    pub fn description(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.8 = value.into();
        self
    }
    /// Set the `description` field to an Option value (optional)
    pub fn maybe_description(mut self, value: Option<S>) -> Self {
        self._fields.8 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `fitClass` field (optional)
    pub fn fit_class(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.9 = value.into();
        self
    }
    /// Set the `fitClass` field to an Option value (optional)
    pub fn maybe_fit_class(mut self, value: Option<S>) -> Self {
        self._fields.9 = value;
        self
    }
}

impl<St, S: BosStr> ItemBuilder<St, S>
where
    St: item_state::State,
    St::Give: item_state::IsUnset,
{
    /// Set the `give` field (required)
    pub fn give(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> ItemBuilder<item_state::SetGive<St>, S> {
        self._fields.10 = Option::Some(value.into());
        ItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `icon` field (optional)
    pub fn icon(mut self, value: impl Into<Option<BlobRef<S>>>) -> Self {
        self._fields.11 = value.into();
        self
    }
    /// Set the `icon` field to an Option value (optional)
    pub fn maybe_icon(mut self, value: Option<BlobRef<S>>) -> Self {
        self._fields.11 = value;
        self
    }
}

impl<St, S: BosStr> ItemBuilder<St, S>
where
    St: item_state::State,
    St::Item: item_state::IsUnset,
{
    /// Set the `item` field (required)
    pub fn item(
        mut self,
        value: impl Into<S>,
    ) -> ItemBuilder<item_state::SetItem<St>, S> {
        self._fields.12 = Option::Some(value.into());
        ItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `kind` field (optional)
    pub fn kind(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.13 = value.into();
        self
    }
    /// Set the `kind` field to an Option value (optional)
    pub fn maybe_kind(mut self, value: Option<S>) -> Self {
        self._fields.13 = value;
        self
    }
}

impl<St, S: BosStr> ItemBuilder<St, S>
where
    St: item_state::State,
    St::Provider: item_state::IsUnset,
{
    /// Set the `provider` field (required)
    pub fn provider(
        mut self,
        value: impl Into<Did<S>>,
    ) -> ItemBuilder<item_state::SetProvider<St>, S> {
        self._fields.14 = Option::Some(value.into());
        ItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `stats` field (optional)
    pub fn stats(mut self, value: impl Into<Option<Data<S>>>) -> Self {
        self._fields.15 = value.into();
        self
    }
    /// Set the `stats` field to an Option value (optional)
    pub fn maybe_stats(mut self, value: Option<Data<S>>) -> Self {
        self._fields.15 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `suppressAs` field (optional)
    pub fn suppress_as(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.16 = value.into();
        self
    }
    /// Set the `suppressAs` field to an Option value (optional)
    pub fn maybe_suppress_as(mut self, value: Option<S>) -> Self {
        self._fields.16 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `suppressClasses` field (optional)
    pub fn suppress_classes(mut self, value: impl Into<Option<Vec<S>>>) -> Self {
        self._fields.17 = value.into();
        self
    }
    /// Set the `suppressClasses` field to an Option value (optional)
    pub fn maybe_suppress_classes(mut self, value: Option<Vec<S>>) -> Self {
        self._fields.17 = value;
        self
    }
}

impl<St: item_state::State, S: BosStr> ItemBuilder<St, S> {
    /// Set the `suppressLayers` field (optional)
    pub fn suppress_layers(mut self, value: impl Into<Option<Vec<S>>>) -> Self {
        self._fields.18 = value.into();
        self
    }
    /// Set the `suppressLayers` field to an Option value (optional)
    pub fn maybe_suppress_layers(mut self, value: Option<Vec<S>>) -> Self {
        self._fields.18 = value;
        self
    }
}

impl<St, S: BosStr> ItemBuilder<St, S>
where
    St: item_state::State,
    St::Title: item_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(
        mut self,
        value: impl Into<S>,
    ) -> ItemBuilder<item_state::SetTitle<St>, S> {
        self._fields.19 = Option::Some(value.into());
        ItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ItemBuilder<St, S>
where
    St: item_state::State,
    St::AcceptedAt: item_state::IsSet,
    St::Give: item_state::IsSet,
    St::Item: item_state::IsSet,
    St::Provider: item_state::IsSet,
    St::Title: item_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Item<S> {
        Item {
            accepted_at: self._fields.0.unwrap(),
            asset: self._fields.1,
            asset_cid: self._fields.2,
            behind_rows: self._fields.3,
            category: self._fields.4,
            channels: self._fields.5,
            colorway: self._fields.6,
            context: self._fields.7,
            description: self._fields.8,
            fit_class: self._fields.9,
            give: self._fields.10.unwrap(),
            icon: self._fields.11,
            item: self._fields.12.unwrap(),
            kind: self._fields.13,
            provider: self._fields.14.unwrap(),
            stats: self._fields.15,
            suppress_as: self._fields.16,
            suppress_classes: self._fields.17,
            suppress_layers: self._fields.18,
            title: self._fields.19.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Item<S> {
        Item {
            accepted_at: self._fields.0.unwrap(),
            asset: self._fields.1,
            asset_cid: self._fields.2,
            behind_rows: self._fields.3,
            category: self._fields.4,
            channels: self._fields.5,
            colorway: self._fields.6,
            context: self._fields.7,
            description: self._fields.8,
            fit_class: self._fields.9,
            give: self._fields.10.unwrap(),
            icon: self._fields.11,
            item: self._fields.12.unwrap(),
            kind: self._fields.13,
            provider: self._fields.14.unwrap(),
            stats: self._fields.15,
            suppress_as: self._fields.16,
            suppress_classes: self._fields.17,
            suppress_layers: self._fields.18,
            title: self._fields.19.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}